#!/usr/bin/env bash
#print 1-100 with multiples of 3,5,and 15 displaying fizz, buzz, or fizzbuzz
for x in {1..100}; do
	if [ $(( x % 15)) == 0 ]; then
		echo "FizzBuzz"
	elif [ $(( x % 3 )) == 0 ]; then
		echo "Fizz"
	elif [ $((x % 5)) == 0 ]; then
		echo "Buzz"
	else
		echo "$x"
	fi
done
